"""empty message

Revision ID: 91894361b2fe
Revises: cfb0943785fd
Create Date: 2024-11-15 20:31:56.292462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91894361b2fe'
down_revision = 'cfb0943785fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_offering_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_offering_id', 'offerings', ['offering_id'], ['offering_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_offering_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_offering_id', 'offerings', ['offering_id'], ['offering_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
