"""empty message

Revision ID: b3498d7bfded
Revises: 
Create Date: 2024-11-11 21:03:29.513745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3498d7bfded'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['clients.client_id'], name='fk_client_id'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('instructors',
    sa.Column('instructor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('instructor_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('lessons',
    sa.Column('lesson_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lesson_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('lesson_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('offerings',
    sa.Column('offering_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.instructor_id'], name='fk_instructor_id'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], name='fk_lesson_id'),
    sa.PrimaryKeyConstraint('offering_id')
    )
    op.create_table('time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=50), nullable=False),
    sa.Column('end_time', sa.String(length=50), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayoftheweek'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], name='fk_lesson_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('BOOKED', 'CANCELED', 'COMPLETED', name='bookingstatus'), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='fk_client_id'),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.offering_id'], name='fk_offering_id'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('schedules',
    sa.Column('schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayoftheweek'), nullable=False),
    sa.Column('start_time', sa.String(length=50), nullable=False),
    sa.Column('end_time', sa.String(length=50), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('time_slot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.instructor_id'], name='instructor_id'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], name='lesson_id'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='location_id'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], name='time_slots.id'),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_table('bookings')
    op.drop_table('time_slots')
    op.drop_table('offerings')
    op.drop_table('locations')
    op.drop_table('lessons')
    op.drop_table('instructors')
    op.drop_table('clients')
    op.drop_table('admin')
    # ### end Alembic commands ###
