"""empty message

Revision ID: cfb0943785fd
Revises: 0c7395164173
Create Date: 2024-11-15 20:29:41.245402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb0943785fd'
down_revision = '0c7395164173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_offering_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_offering_id', 'offerings', ['offering_id'], ['offering_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_offering_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_offering_id', 'offerings', ['offering_id'], ['offering_id'])

    # ### end Alembic commands ###
