"""empty message

Revision ID: f7ab935c39bd
Revises: 8027b24450aa
Create Date: 2024-11-12 13:25:45.981780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ab935c39bd'
down_revision = '8027b24450aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint('instructor_id', type_='foreignkey')
        batch_op.drop_constraint('location_id', type_='foreignkey')
        batch_op.drop_column('instructor_id')
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')
        batch_op.drop_column('day_of_week')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('day_of_week', sa.VARCHAR(length=9), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('instructor_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('location_id', 'locations', ['location_id'], ['location_id'])
        batch_op.create_foreign_key('instructor_id', 'instructors', ['instructor_id'], ['instructor_id'])

    # ### end Alembic commands ###
